
# **Introduction - Data Types and Data Structures**

Strings in python are identified as a contiguous set of characters represented in either single quotes (' ') or double quotes (" ").


In [2]:
my_string1 = 'Welcome to'
my_string2 = "QuantConnect"
print(my_string1 + ' ' + my_string2)


Welcome to QuantConnect


In [3]:
my_string1 = 'Hola'
my_string2 = "Mundo XD"
print(my_string1 + ' ' + my_string2)


Hola Mundo XD


An integer is a round number with no values after the decimal point.

In [4]:
my_int = 10
print(my_int)
print(type(my_int))

10
<class 'int'>


In [5]:
my_int = 21
print(my_int)
print(type(my_int))

21
<class 'int'>


The built-in function int() can convert a string into an integer.

In [6]:
my_string = "100"
print(type(my_string))
my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>


In [7]:
my_string = "21"
print(type(my_string))
my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>


A floating point number, or a float, is a real number in mathematics. In Python we need to include a value after a decimal point to define it as a float.

In [8]:
my_float = 1.0
print(type(my_float))
my_int = 1
print(type(my_int))

<class 'float'>
<class 'int'>


In [9]:
my_float = 2.1
print(type(my_float))
my_int = 1
print(type(my_int))

<class 'float'>
<class 'int'>


As you can see above, if we don't include a decimal value, the variable would be defined as an integer. The built-in function float() can convert a string or an integer into a float.

In [10]:
my_string = "100"
my_float = float(my_string)
print(type(my_float))

<class 'float'>


In [11]:
my_string = "210"
my_float = float(my_string)
print(type(my_float))

<class 'float'>


A boolean, or bool, is a binary variable. Its value can only be True or False. It is useful when we do some logic operations, which would be covered in our next chapter.

In [12]:
my_bool = False
print(my_bool)
print(type(my_bool))

False
<class 'bool'>


In [13]:
my_bool = True
print(my_bool)
print(type(my_bool))

True
<class 'bool'>


The basic math operators in python are demonstrated below:

In [14]:
print("Addition ", 1+1)
print("Subtraction ", 5-2)
print("Multiplication ", 2*3)
print("Division", 10/2)
print("exponent", 2**3)

Addition  2
Subtraction  3
Multiplication  6
Division 5.0
exponent 8


In [15]:
print("Addition ", 2+1)
print("Subtraction ", 2-1)
print("Multiplication ", 2*1)
print("Division", 2/1)
print("exponent", 2**1)

Addition  3
Subtraction  1
Multiplication  2
Division 2.0
exponent 2


List
A list is an ordered collection of values. A list is mutable, which means you can change a list's value without changing the list itself. Creating a list is simply putting different comma-separated values between square brackets.

In [16]:
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)

['Quant', 'Connect', 1, 2, 3]


In [17]:
my_list = ['Saludos', 'a todos', 2,1,0]
print(my_list)

['Saludos', 'a todos', 2, 1, 0]


The values in a list are called "elements". We can access list elements by indexing. Python index starts from 0. So if you have a list of length n, the index of the first element will be 0, and that of the last element will be n − 1. By the way, the length of a list can be obtained by the built-in function len().

In [18]:
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))
print(my_list[0])
print(my_list[len(my_list) - 1])

5
Quant
3


In [19]:
my_list = ['Saludos', 'a todos', 2,1,0]
print(len(my_list))
print(my_list[0])
print(my_list[len(my_list) - 1])

5
Saludos
0


You can also change the elements in the list by accessing an index and assigning a new value.

In [20]:
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'go'
print(my_list)

['Quant', 'Connect', 'go', 2, 3]


In [21]:
my_list = ['Saludos','a todos',2,1,0]
my_list[2] = 'aqui'
print(my_list)

['Saludos', 'a todos', 'aqui', 1, 0]


A list can also be sliced with a colon:

In [22]:
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:3])

['Connect', 1]


In [23]:
my_list = ['saludos','a todos',2,1,0]
print(my_list[1:3])

['a todos', 2]


The slice starts from the first element indicated, but excludes the last element indicated. Here we select all elements starting from index 1, which refers to the second element:

In [24]:
print(my_list[1:])

['a todos', 2, 1, 0]


In [25]:
print(my_list[3:])

[1, 0]


And all elements up to but excluding index 3:

In [26]:
print(my_list[:3])

['saludos', 'a todos', 2]


In [27]:
print(my_list[:2])

['saludos', 'a todos']


If you wish to add or remove an element from a list, you can use the append() and remove() methods for lists as follows:

In [28]:
my_list = ['Hello', 'Quant']
my_list.append('Hello')
print(my_list)
my_list.remove('Hello')
print(my_list)

['Hello', 'Quant', 'Hello']
['Quant', 'Hello']


In [29]:
my_list = ['Saludos', 'a todos']
my_list.append('Saludos')
print(my_list)
my_list.remove('Saludos')
print(my_list)

['Saludos', 'a todos', 'Saludos']
['a todos', 'Saludos']


Tuple
A tuple is a data structure type similar to a list. The difference is that a tuple is immutable, which means you can't change the elements in it once it's defined. We create a tuple by putting comma-separated values between parentheses.

In [30]:
my_tuple = ('Welcome','to','QuantConnect')
print(my_tuple[1:])

('to', 'QuantConnect')


In [31]:
my_tuple = ('Saludos','a','todos')
print(my_tuple[1:])

('a', 'todos')


Set
A set is an unordered collection with no duplicate elements. The built-in function set() can be used to create sets.

In [32]:
stock_list = ['AAPL','GOOG','IBM','AAPL','IBM','FB','F','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'GOOG', 'AAPL', 'IBM', 'FB', 'F'}


In [33]:
stock_list = ['Saludos','a','todos','Saludos','todos','aqui','presentes','a']
stock_set = set(stock_list)
print(stock_set)

{'todos', 'presentes', 'aqui', 'Saludos', 'a'}


Dictionary
A dictionary is one of the most important data structures in Python. Unlike sequences which are indexed by integers, dictionaries are indexed by keys which can be either strings or floats.

A dictionary is an unordered collection of key : value pairs, with the requirement that the keys are unique. We create a dictionary by placing a comma-separated list of key : value pairs within the braces.

After defining a dictionary, we can access any value by indicating its key in brackets.



In [34]:
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}
print(my_dic['GOOG'])

Alphabet


In [35]:
my_dic = {'Saludos': 'Hola', 'a': 'para', 'todos': ':D'}
print(my_dic['a'])

para


We can also change the value associated with a specified key:

In [36]:
my_dic['GOOG'] = 'Alphabet Company'
print(my_dic['GOOG'])

Alphabet Company


In [37]:
my_dic['todos'] = 'ti'
print(my_dic['todos'])

ti


The built-in method of the dictionary object dict.keys() returns a list of all the keys used in the dictionary.

In [38]:
print(my_dic.keys())

dict_keys(['Saludos', 'a', 'todos', 'GOOG'])


A string is an immutable sequence of characters. It can be sliced by index just like a tuple:

In [39]:
my_str = 'Welcome to QuantConnect'
print(my_str[8:])

to QuantConnect


In [40]:
my_str = 'Saludos a todos'
print(my_str[5:])

os a todos


There are many methods associated with strings. We can use string.count() to count the occurrences of a character in a string, use string.find() to return the index of a specific character, and use string.replace() to replace characters.

In [41]:
print("Counting the number of e's in this sentence".count('e'))
print('The first time e appears in this sentence'.find('e'))
print('all the a in this sentence now becomes e'.replace('a','e'))

6
2
ell the e in this sentence now becomes e


In [42]:
print("Saludos a todos".count('o'))
print('Hola para ti'.find('a'))
print('Bienvenido a este lugar'.replace('e','u'))

3
3
Biunvunido a ustu lugar


The most commonly used method for strings is string.split(). This method will split the string by the indicated character and return a list:

In [43]:
Time = '2016-04-01 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)
hour = time.split(':')[0]
print(hour)

2016-04-01 09:43:00
09


In [44]:
Time = '2021-10-18 11:18:25'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)
hour = time.split(':')[0]
print(hour)

2021-10-18 11:18:25
11


We can replace parts of a string by our variable. This is called string formatting.

In [45]:
my_time = 'Hour: {}, Minute: {}'.format(9, 43)
print(my_time)

Hour: 9, Minute: 43


In [46]:
my_time = 'Hora: {}, Minuto: {}'.format(10, 25)
print(my_time)

Hora: 10, Minuto: 25


Another way to format a string is to use the % symbol.

In [47]:
print ('pi is %f' % 3.14)
print('%s to %s' % ('Welcome', 'QuantConnect'))

pi is 3.140000
Welcome to QuantConnect


In [48]:
print ('mi codigo es %f' % 32.251)
print('%s a %s' % ('Saludos', 'todos'))

mi codigo es 32.251000
Saludos a todos


# **Logical Operations**

Like most programming languages, Python has comparison operators:

In [49]:
print(1 == 0)   # 1 equals 0
print(1 == 1)    # 1 equals 1
print(1 != 0)   # 1 is not equal to 0
print(5 >= 5)    # 5 is greater than or equal to 5
print(5 >= 6)    # 5 is greater than or equal to 6

False
True
True
True
False


In [50]:
print(4 == 8)
print(6 == 6)
print(15 != 40)
print(4 >= 3)
print(8 >= 14)  

False
True
True
True
False


Each statement above has a boolean value, which must be either True or False, but not both.

We can combine simple statements P and Q to form complex statements using logical operators:

The statement "P and Q" is true if both P and Q are true, otherwise it is false.
The statement "P or Q" is false if both P and Q are false, otherwise it is true.
The statement "not P" is true if P is false, and vice versa.

In [51]:
print(2 > 1 and 3 > 2)
print(2 > 1 and 3 < 2)
print(2 > 1 or  3 < 2)
print(2 < 1 and 3 < 2)

True
False
True
False


In [52]:
print(14 > 7 and 7 > 4)
print(14 > 7 and 7 < 4)
print(8 > 3 or  8 < 3)
print(12 < 1 and 13 < 2)

True
False
True
False


When dealing with a very complex logical statement that involves in several statements, we can use brackets to separate and combine them.

In [53]:
print((3 > 2 or 1 < 3) and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))
print(3 > 2 or 1 < 3 and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))

False
True


In [54]:
print((25 > 8 and 1 < 3) or (1!=25 and 16>3) or ( 25 < 2 and not 45 < 36 or (1!=3 and 4>3)))
print(32 > 3 and 2 < 1 or (6!=5 and 7>8) and not ( 8 < 6 and not 4 < 5 and (56!=65 or 4>34)))

True
False


If Statement
An if statement executes a segment of code only if its condition is true. A standard if statement consists of 3 segments: if, elif and else.

In [55]:
i = 0
if i == 0: print('i == 0 is True')

i == 0 is True


In [56]:
i = 5
if i == 5: print('i == 5 is True')

i == 5 is True


As we mentioned above, we can write some complex statements here:

In [57]:
p = 8 > 0
q = 14 > 5
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

p and q is true


Loop Structure
Loops are an essential part of programming. The "for" and "while" loops run a block of code repeatedly.

While Loop
A "while" loop will run repeatedly until a certain condition has been met.

In [58]:
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


In [59]:
i = 3
while i < 5:
    print(i)
    i += 1

3
4


For Loop
A "for" loop will iterate over a sequence of value and terminate when the sequence has ended.

In [60]:
for x in [1,2,3,4,5]: print(x)

1
2
3
4
5


In [61]:
for x in [2,3,4,5,6]: print(x)

2
3
4
5
6


We can also add if statements in a for loop. Here is a real example from our pairs trading algorithm:

In [62]:
stocks = ['uno','dos','tres','cuatro','c','s', 'r', 'oc']
selected = ['uno','c']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print(new_list)

['dos', 'tres', 'cuatro', 's', 'r', 'oc']


Break and continue
These are two commonly used commands in a for loop. If "break" is triggered while a loop is executing, the loop will terminate immediately:

In [63]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    print (stock)
    if stock == 'FB': break

AAPL
GOOG
IBM
FB


In [64]:
stocks = ['uno','dos','tres','cuatro','c','s', 'r', 'oc']
for stock in stocks:
    print (stock)
    if stock == 'tres': break

uno
dos
tres


The "continue" command tells the loop to end this iteration and skip to the next iteration:

In [65]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock == 'FB': continue
    print (stock)

AAPL
GOOG
IBM
F
V
G
GE


In [66]:
stocks = ['uno','dos','tres','cuatro','c','s', 'r', 'oc']
for stock in stocks:
    if stock == 'tres': continue
    print (stock)

uno
dos
cuatro
c
s
r
oc


List Comprehension
List comprehension is a Pythonic way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence. For example, if we want to create a list of squares using for loop:

In [67]:
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print (squares)

[1, 4, 9, 16, 25]


In [68]:
squares = []
for i in [12,2,32,44,5]:
    squares.append(i**2)
print (squares)

[144, 4, 1024, 1936, 25]



Using list comprehension:

In [69]:
foo = [1,2,3,4,5]
squares = [x**2 for x in foo]
print (squares)

[1, 4, 9, 16, 25]


In [70]:
foo = [12,2,32,44,5]
squares = [x**2 for x in foo]
print (squares)

[144, 4, 1024, 1936, 25]


Recall the example above where we used a for loop to select stocks. Here we use list comprehension:

In [71]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = [x for x in stocks if x not in selected]
print (new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [72]:
stocks = ['uno','dos','tres','cuatro','c','s', 'r', 'oc']
selected = ['dos','c','s']
new_list = [x for x in stocks if x not in selected]
print (new_list)

['uno', 'tres', 'cuatro', 'r', 'oc']


A list comprehension consists of square brackets containing an expression followed by a "for" clause, and possibly "for" or "if" clauses. For example:

In [73]:
print([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB']
                                for y in ['F','V','G','GE'] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs F', 'FB vs V', 'FB vs G', 'FB vs GE']


In [74]:
print([(x, y) for x in [3,2,1] for y in [4,2,8] if x != y])
print([str(x) + ' vs ' + str(y) for x in ['uno','dos','tres','cuatro']
                                for y in ['c','s', 'r', 'oc'] if x != y])

[(3, 4), (3, 2), (3, 8), (2, 4), (2, 8), (1, 4), (1, 2), (1, 8)]
['uno vs c', 'uno vs s', 'uno vs r', 'uno vs oc', 'dos vs c', 'dos vs s', 'dos vs r', 'dos vs oc', 'tres vs c', 'tres vs s', 'tres vs r', 'tres vs oc', 'cuatro vs c', 'cuatro vs s', 'cuatro vs r', 'cuatro vs oc']


# **Functions and Objective-Oriented Programming**





Functions
A function is a reusable block of code. We can use a function to output a value, or do anything else we want. We can easily define our own function by using the keyword "def".

In [75]:
def product(x,y):
    return x*y
print(product(2,3))
print(product(5,10))

6
50


In [76]:
def sum(x,y):
    return x+y
print(sum(2,3))
print(sum(5,10))

5
15


The keyword "def" is followed by the function name and the parenthesized list of formal parameters. The statements that form the body of the function start at the next line, and must be indented. The product() function above has "x" and "y" as its parameters. A function doesn't necessarily have parameters:

In [77]:
def say_hi():
    print("Welcome to QuantConnect")
say_hi()

Welcome to QuantConnect


In [78]:
def saludos():
    print("Saludos a todos")
saludos()

Saludos a todos


Built-in Function
range() is a function that creates a list containing an arithmetic sequence. It's often used in for loops. The arguments must be integers. If the "step" argument is omitted, it defaults to 1.

In [79]:
print ([x for x in range(10)])
print ([x for x in range(1,10)])
print ([x for x in range(1,11,2)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]


In [80]:
print ([x for x in range(8)])
print ([x for x in range(3,8)])
print ([x for x in range(4,8,3)])

[0, 1, 2, 3, 4, 5, 6, 7]
[3, 4, 5, 6, 7]
[4, 7]


len() is another function used together with range() to create a for loop. This function returns the length of an object. The argument must be a sequence or a collection.

In [81]:
tickers = ['uno','dos','tres','cuatro','c','s', 'r', 'oc']
print ("Los elementos enumerados son {}".format(len(tickers)))
for k in range(len(tickers)):
    print (k + 1, tickers[k])

Los elementos enumerados son 8
1 uno
2 dos
3 tres
4 cuatro
5 c
6 s
7 r
8 oc


map() is a function that applies a specific function to every item of a sequence or collection, and returns a list of the results.

In [82]:
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2]


In [83]:
tickers = ['uno','dos','tres','cuatro','c','s', 'r', 'oc']
print(list(map(len,tickers)))

[3, 3, 4, 6, 1, 1, 1, 2]


The lambda operator is a way to create small anonymous functions. These functions are just needed where they have been created. For example:

In [84]:
print(list(map(lambda x: x**2, range(10))))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [85]:
print(list(map(lambda x: x**3, range(6))))

[0, 1, 8, 27, 64, 125]


map() can be applied to more than one list. The lists have to have the same length.

In [86]:
print(list(map(lambda x, y: x+y, [1,2,3,4,5], [5,4,3,2,1])))

[6, 6, 6, 6, 6]


In [87]:
print(list(map(lambda x, y: x-y, [1,2,3,4,5], [5,4,3,2,1])))

[-4, -2, 0, 2, 4]


sorted() takes a list or set and returns a new sorted list:

In [88]:
sorted([5,2,3,4,1])

[1, 2, 3, 4, 5]

In [89]:
sorted([11,14,18,22,36])

[11, 14, 18, 22, 36]

We can add a "key" parameter to specify a function to be called on each list element prior to making comparisons. For example:

In [90]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1])

[('MSFT', 69),
 ('WMT', 75.32),
 ('AAPL', 144.09),
 ('FB', 150),
 ('GOOGL', 911.71)]

In [91]:
price_list = [('UNO', 22.3), ('DOS', 41), ('TRES', 87.5), ('C', 144), ('CIN', 3.14)]
sorted(price_list, key = lambda x: x[1])

[('CIN', 3.14), ('UNO', 22.3), ('DOS', 41), ('TRES', 87.5), ('C', 144)]

By default the values are sorted by ascending order. We can change it to descending by adding an optional parameter "reverse'.

In [92]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1], reverse = True)

[('GOOGL', 911.71),
 ('FB', 150),
 ('AAPL', 144.09),
 ('WMT', 75.32),
 ('MSFT', 69)]

In [93]:
price_list = [('UNO', 22.3), ('DOS', 41), ('TRES', 87.5), ('C', 144), ('CIN', 3.14)]
sorted(price_list, key = lambda x: x[1],reverse = True)

[('C', 144), ('TRES', 87.5), ('DOS', 41), ('UNO', 22.3), ('CIN', 3.14)]

Lists also have a function list.sort(). This function takes the same "key" and "reverse" arguments as sorted(), but it doesn't return a new list.

In [94]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
price_list.sort(key = lambda x: x[1])
print (price_list)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]


In [95]:
price_list = [('UNO', 22.3), ('DOS', 41), ('TRES', 87.5), ('C', 144), ('CIN', 3.14)]
price_list.sort(key = lambda x: x[1])
print (price_list)

[('CIN', 3.14), ('UNO', 22.3), ('DOS', 41), ('TRES', 87.5), ('C', 144)]


Class
A class is a type of data, just like a string, float, or list. When we create an object of that data type, we call it an instance of a class.

In Python, everything is an object - everything is an instance of some class. The data stored inside an object are called attributes, and the functions which are associated with the object are called methods.

For example, as mentioned above, a list is an object of the "list" class, and it has a method list.sort().

We can create our own objects by defining a class. We would do this when it's helpful to group certain functions together. For example, we define a class named "Stock" here:

In [96]:
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print (self.rate_return)

In [97]:
apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)

In [98]:
apple.ticker
google.print_return()
google.update(912.8,913.4)
google.print_return()

0.014465338822744034
0.0006573181419806673


In [99]:
apple.ceo = 'Tim Cook'
apple.ceo

'Tim Cook'

In [100]:
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [101]:
class Producto:
    def __init__(self, nombre, referencia, precio, inventario):
        self.nombre = nombre
        self.referencia = referencia
        self.precio = precio
        self.inventario = inventario
        self.valor_inventario = float((precio)*inventario)

    def update(self, precio, inventario):
        self.precio = precio
        self.inventario = inventario
        self.valor_inventario = float((precio)*inventario)

    def print_return(self):
        print (self.rate_return)

In [102]:
HG11  = Producto('AUDIFONOS HG11', 'HG11', 180000, 25)
VX7 = Producto('MOUSE VX7', 'VX7', 59000, 2)

In [103]:
HG11.EAN = 6525454522
HG11.EAN

6525454522

In [104]:
dir(HG11)

['EAN',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'inventario',
 'nombre',
 'precio',
 'print_return',
 'referencia',
 'update',
 'valor_inventario']

Inheritance
Inheritance is a way of arranging classes in a hierarchy from the most general to the most specific. A "child" class is a more specific type of a "parent" class because a child class will inherit all the attribues and methods of its parent. For example, we define a class named "Child" which inherits "Stock":

In [105]:
class Child(Stock):
    def __init__(self, name):
        self.name = name

In [106]:
aa = Child('AA')
print (aa.name)
aa.update(100, 102)
print (aa.open)
print (aa.close)
print (aa.print_return())

AA
100
102
0.020000000000000018
None


In [107]:
class Producto2(Producto):
    def __init__(self, nombre):
        self.nombre = nombre

In [108]:
HG15 = Producto2('ADIFONOS HG15')
print(HG15.nombre)
HG15.update(140000, 16)
print(HG15.precio)
print(HG15.inventario)
print(HG15.valor_inventario)

ADIFONOS HG15
140000
16
2240000.0


#**NumPy and Basic Pandas**

NumPy
NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It also has strong integration with Pandas, which is another powerful tool for manipulating financial data.

Python packages like NumPy and Pandas contain classes and methods which we can use by importing the package:

In [109]:
import numpy as np

Basic NumPy Arrays
A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. Here we make an array by passing a list of Apple stock prices:

In [110]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print (price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [111]:
precio_list = [22.5,22.65,41.5,155.4]
precio_array = np.array(precio_list)
print (precio_array, type(precio_array))

[ 22.5   22.65  41.5  155.4 ] <class 'numpy.ndarray'>


Notice that the type of array is "ndarray" which is a multi-dimensional array. If we pass np.array() a list of lists, it will create a 2-dimensional array.

In [112]:
Ar = np.array([[1,3], [2,4]])
print (Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [113]:
Ar = np.array([[11,33,65], [22,44,55]])
print (Ar, type(Ar))

[[11 33 65]
 [22 44 55]] <class 'numpy.ndarray'>


We get the dimensions of an ndarray using the .shape attribute:

In [114]:
print( Ar.shape)

(2, 3)


In [115]:
print( Ar.shape)

(2, 3)


If we create an 2-dimensional array (i.e. matrix), each row can be accessed by index:

In [116]:
print (Ar[0])
print( Ar[1])

[11 33 65]
[22 44 55]


In [117]:
print (Ar[0])
print( Ar[1])

[11 33 65]
[22 44 55]


If we want to access the matrix by column instead:

In [118]:
print ('First column:', Ar[:,0])
print ('Second column:', Ar[:,1])

First column: [11 22]
Second column: [33 44]


In [119]:
print ('First column:', Ar[:,0])
print ('Second column:', Ar[:,1])
print ('Third column:', Ar[:,2])

First column: [11 22]
Second column: [33 44]
Third column: [65 55]


Array Functions
Some functions built in NumPy that allow us to perform calculations on arrays. For example, we can apply the natural logarithm to each element of an array:

In [120]:
np.log(price_array)

array([4.96793654, 4.98244156, 4.9675886 , 4.96995218, 4.96633504,
       4.96018375])

In [121]:
np.log(precio_array)

array([3.11351531, 3.12015985, 3.72569343, 5.04600244])

Other functions return a single value:

In [122]:
np.mean(price_array)
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

0.9673790478515796
863.38
145.83


In [123]:
np.mean(precio_array)
print(np.std(precio_array))
print(np.sum(precio_array))
print(np.max(precio_array))

55.325473054913864
242.05
155.4


Pandas
Pandas is one of the most powerful tools for dealing with financial data. First we need to import Pandas:

In [124]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

Series
Series is a one-dimensional labeled array capable of holding any data type (integers, strings, float, Python object, etc.)

We create a Series by calling pd.Series(data), where data can be a dictionary, an array or just a scalar value.

In [ ]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print(s)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [ ]:
precio = [22.5,22.65,41.5,155.4]
s = pd.Series(precio)
print(s)

0     22.50
1     22.65
2     41.50
3    155.40
dtype: float64


We can customize the indices of a new Series:



In [ ]:
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print (s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [ ]:
s2 = pd.Series(precio, index = ['w', 'x', 'y', 'z'])
print (s2)

w     22.50
x     22.65
y     41.50
z    155.40
dtype: float64


Or we can change the indices of an existing Series:

In [ ]:
s.index = [6,5,4,3,2,1]
print (s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [ ]:
s2.index = [4,3,2,1]
print (s2)

4     22.50
3     22.65
2     41.50
1    155.40
dtype: float64


Series is like a list since it can be sliced by index:

In [ ]:
print (s[1:])
print (s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [ ]:
print (s2[2:])
print (s2[:-3])

2     41.5
1    155.4
dtype: float64
4    22.5
dtype: float64


Series is also like a dictionary whose values can be set or fetched by index label:

In [ ]:
print (s[4])
s[4] = 0
print (s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [ ]:
print (s2[2])
s2[2] = 0
print (s2)

41.5
4     22.50
3     22.65
2      0.00
1    155.40
dtype: float64


Series can also have a name attribute, which will be used when we make up a Pandas DataFrame using several series.

In [ ]:
s = pd.Series(price, name = 'Apple Prices')
print (s)
print (s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
Apple Prices


In [ ]:
s2 = pd.Series(precio, name = 'Precios de productos')
print ((s2))
print ((s2.name))

0     22.50
1     22.65
2     41.50
3    155.40
Name: Precios de productos, dtype: float64
Precios de productos


We can get the statistical summaries of a Series:

In [ ]:
print (s.describe())

count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64


In [ ]:
print (s2.describe())

count      4.000000
mean      60.512500
std       63.884354
min       22.500000
25%       22.612500
50%       32.075000
75%       69.975000
max      155.400000
Name: Precios de productos, dtype: float64


Time Index
Pandas has a built-in function specifically for creating date indices: pd.date_range(). We use it to create a new index for our Series:

In [ ]:
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print (time_index)
s.index = time_index
print (s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [ ]:
time_index2 = pd.date_range('2017-01-01', periods = len(s2), freq = 'D')
print (time_index2)
s2.index = time_index2
print (s2)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04'], dtype='datetime64[ns]', freq='D')
2017-01-01     22.50
2017-01-02     22.65
2017-01-03     41.50
2017-01-04    155.40
Freq: D, Name: Precios de productos, dtype: float64


Series are usually accessed using the iloc[] and loc[] methods. iloc[] is used to access elements by integer index, and loc[] is used to access the index of the series.

iloc[] is necessary when the index of a series are integers, take our previous defined series as example:

In [ ]:
s.index = [6,5,4,3,2,1]
print (s)
print (s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62


In [ ]:
s2.index = [4,3,2,1]
print (s2)
print (s2[1])

4     22.50
3     22.65
2     41.50
1    155.40
Name: Precios de productos, dtype: float64
155.4


If we intended to take the second element of the series, we would make a mistake here, because the index are integers. In order to access to the element we want, we use iloc[] here:

In [ ]:
print (s.iloc[1])

145.83


In [ ]:
print (s2.iloc[1])

22.65


While working with time series data, we often use time as the index. Pandas provides us with various methods to access the data by time index.

In [ ]:
s.index = time_index
print (s['2017-01-03'])

143.68


In [ ]:
s2.index = time_index2
print (s2['2017-01-03'])

41.5


We can even access to a range of dates:

In [ ]:
print (s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [ ]:
print (s2['2017-01-02':'2017-01-05'])

2017-01-02     22.65
2017-01-03     41.50
2017-01-04    155.40
Freq: D, Name: Precios de productos, dtype: float64


Series[] provides us a very flexible way to index data. We can add any condition in the square brackets:

In [ ]:
print (s[s < np.mean(s)])
print (s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Prices, dtype: float64
2017-01-04    144.02
Freq: D, Name: Apple Prices, dtype: float64


In [ ]:
print (s2[s2 < np.mean(s2)])
print (s2[(s2 > np.mean(s2)) & (s2 < np.mean(s2) + 1.64*np.std(s2))])

2017-01-01    22.50
2017-01-02    22.65
2017-01-03    41.50
Freq: D, Name: Precios de productos, dtype: float64
Series([], Freq: D, Name: Precios de productos, dtype: float64)
